# Module Assignment 3 Project for Course BAN6800 (Business Analytics Capstone)

- **Task 0** : Business Analytics Project-Ready Dataset

### <u>1.0 Intro</u>
This assignment is about getting ready the dataset that will be used in the Customer Segmentation project for Cognitive Software Solutions. The company has three branches which produces several products. All the products of the company are grouped into five categories which are (Saas, Cloud Services, Security, Artificial Intelligence and Development Tools). Each of these categories stores data on a seperate server. A total of these different reports is expected to be 100,000 records.

In [263]:
# Import the neccessary libraries

import pandas as pd, warnings
from glob import glob
from sklearn.preprocessing import StandardScaler, LabelEncoder
warnings.filterwarnings('ignore', category=pd.errors.SettingWithCopyWarning)

### <u>1.1 Input Data (Data Integration)</u>
First, we need to read all the different dataset from all the five categories and carry out a Data Integration process to consolidate to one dataset.

In [264]:
# Read the directory and fetch all the file names of the category reports using the glob() function to form a list
category_files = glob(pathname="subsidiary_reports/Cognitive*")
print(category_files)

['subsidiary_reports/Cognitive_Development_Tools_Report.csv', 'subsidiary_reports/Cognitive_Saas_Report.csv', 'subsidiary_reports/Cognitive_Security_Report.csv', 'subsidiary_reports/Cognitive_Artificial_Intelligence_Report.csv', 'subsidiary_reports/Cognitive_Cloud_Services_Report.csv']

In [265]:
# Import all the category files and merged them into one file using the concat() function 
dataset = pd.concat((pd.read_csv(filepath_or_buffer=file) for file in category_files), ignore_index=True)

In [266]:
# Confirm if Dataframe has been fully loaded
dataset.head(n=5)

,Customer_ID,Order_ID,Subscription_Date,Product_ID,Product_Name,Category,Subscription_Type,Usage_Frequency,Revenue_Per_Customer,Payment_Plan,Discount_Applied,Support_Tickets,Feature_Adoption,Last_Login,Churn_Status,Customer_Tenure,Customer_Satisfaction,Marketing_Channel,Contract_Renewal,Num_Logins_Last_Month
0,2454.0,1.0,03/07/2023,19,ScriptEase,Development Tools,Basic,Monthly,2097.0,Annual,24,19,36,10/12/2023,0,9,3,Referral,0,25
1,2167.0,5.0,20/09/2022,18,DevSync,Development Tools,Enterprise,Weekly,324.0,Annual,18,33,84,08/05/2023,0,5,5,Referral,0,25
2,2063.0,6.0,26/10/2023,19,ScriptEase,Development Tools,Enterprise,Daily,1701.0,Lifetime,29,28,37,26/10/2023,0,8,2,Referral,0,7
3,4211.0,22.0,22/02/2022,19,ScriptEase,Development Tools,Enterprise,Daily,3649.0,Lifetime,17,27,90,23/06/2023,0,8,2,Direct,1,17
4,1636.0,24.0,03/11/2022,19,ScriptEase,Development Tools,Enterprise,Monthly,2047.0,Annual,25,5,23,12/08/2023,0,9,5,Advertisement,0,14

In [267]:
# Confirm the number of rows and colums to validate the number of expected records
dataset.shape

(100000, 20)

With the shape of the dataset being (100000, 20) has confirmed that all the datasets were integrated and has loaded successfully !

### <u>2.0 Understanding the dataset</u>
Next, we start by preparing the dataset for analysis by doing data cleansing and checking out for inconsistencies.

In [268]:
# Checking out the properties of the dataset
print(dataset.info(verbose=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer_ID            99993 non-null   float64
 1   Order_ID               99999 non-null   float64
 2   Subscription_Date      100000 non-null  object
 3   Product_ID             100000 non-null  int64
 4   Product_Name           100000 non-null  object
 5   Category               100000 non-null  object
 6   Subscription_Type      99998 non-null   object
 7   Usage_Frequency        100000 non-null  object
 8   Revenue_Per_Customer   99999 non-null   float64
 9   Payment_Plan           99995 non-null   object
 10  Discount_Applied       100000 non-null  int64
 11  Support_Tickets        100000 non-null  int64
 12  Feature_Adoption       100000 non-null  int64
 13  Last_Login             100000 non-null  object
 14  Churn_Status           100000 non-null  int64
 15  Customer_Tenure        100000 non-null  int64
 16  Customer_Satisfaction  100000 non-null  int64
 17  Marketing_Channel      99999 non-null   object
 18  Contract_Renewal       100000 non-null  int64
 19  Num_Logins_Last_Month  100000 non-null  int64
dtypes: float64(3), int64(9), object(8)
memory usage: 15.3+ MB
None

In [269]:
dataset.describe()

,Customer_ID,Order_ID,Product_ID,Revenue_Per_Customer,Discount_Applied,Support_Tickets,Feature_Adoption,Churn_Status,Customer_Tenure,Customer_Satisfaction,Contract_Renewal,Num_Logins_Last_Month
count,99993.000000,99999.000000,100000.000000,99999.000000,100000.00000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2498.455872,50000.171182,10.472070,2527.351314,14.52636,24.47180,59.448800,0.150050,4.998220,3.005540,0.299670,14.508260
std,1442.375827,28868.030051,5.763226,1425.947481,8.66513,14.45266,23.056294,0.357122,2.584694,1.413177,0.458116,8.654375
min,1.000000,1.000000,1.000000,50.000000,0.00000,0.00000,20.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,1249.000000,25000.500000,5.000000,1292.000000,7.00000,12.00000,39.000000,0.000000,3.000000,2.000000,0.000000,7.000000
50%,2500.000000,49999.000000,10.000000,2525.000000,15.00000,24.00000,59.000000,0.000000,5.000000,3.000000,0.000000,15.000000
75%,3746.000000,75000.500000,15.000000,3760.500000,22.00000,37.00000,79.000000,0.000000,7.000000,4.000000,1.000000,22.000000
max,5000.000000,100000.000000,20.000000,4999.000000,29.00000,49.00000,99.000000,1.000000,9.000000,5.000000,1.000000,29.000000

In [270]:
# Describing the dataset using object view
dataset.describe(include=["object"])

,Subscription_Date,Product_Name,Category,Subscription_Type,Usage_Frequency,Payment_Plan,Last_Login,Marketing_Channel
count,100000,100000,100000,99998,100000,99995,100000,99999
unique,2738,20,5,4,3,4,426,5
top,2025-01-31,SecureAuth,SaaS,Pro,Weekly,Monthly,31/07/2023,Social Media
freq,104,5099,20120,25189,33715,33362,277,20140

In [271]:
# Checking if there is a nmissing values in the dataset
print(dataset.isnull().values.any())

True

The checking of the missing value is True, which means there exist missing values in any of the colum

In [272]:
# Summary of all the columns and the number of missing values for each column
print(dataset.isnull().sum())

Customer_ID              7
Order_ID                 1
Subscription_Date        0
Product_ID               0
Product_Name             0
Category                 0
Subscription_Type        2
Usage_Frequency          0
Revenue_Per_Customer     1
Payment_Plan             5
Discount_Applied         0
Support_Tickets          0
Feature_Adoption         0
Last_Login               0
Churn_Status             0
Customer_Tenure          0
Customer_Satisfaction    0
Marketing_Channel        1
Contract_Renewal         0
Num_Logins_Last_Month    0
dtype: int64

### 3.0 Data Cleansing begins at this point


### a. Handling Missing value
There are missing values in some of the data columns including the Customer ID column. Next we need to handle the missing data.
1. Remove the missing row in the Customer ID column and Order ID as there is no way to resolve which customer or Order has the records.
2. Use imputation method of mean, median and mode of each column to fill the other missing value on other columns.

In [273]:
# Drop the records that has the missing value for Customers and Orders.
dataset = dataset.dropna(subset=["Customer_ID", "Order_ID"])

In [274]:
# Handle missing value using mean, median and mode imputation for numerical and categorical data
dataset["Subscription_Type"] = dataset["Subscription_Type"].fillna(dataset["Subscription_Type"].mode()[0])
dataset["Revenue_Per_Customer"] = dataset["Revenue_Per_Customer"].fillna(round(dataset["Revenue_Per_Customer"].mean(), 1))
dataset["Payment_Plan"] = dataset["Payment_Plan"].fillna(dataset["Payment_Plan"].mode()[0])
dataset["Marketing_Channel"] = dataset["Marketing_Channel"].fillna(dataset["Marketing_Channel"].mode()[0])

In [275]:
# Checking if there is a nmissing values in the dataset
print(dataset.isnull().values.any())

False

### b. Handling Inconsistent Data
There is always inconsistencies with different date format. So we will enforce validations to be sure every date colum has same format.
1. Next step is to check out the two date columns and enforce validation

In [276]:
# We will try and format all the data using mixed attribute to dandle each format seperately
dataset['Subscription_Date'] = pd.to_datetime(dataset['Subscription_Date'], format='mixed').dt.strftime('%Y-%m-%d')


dataset['Last_Login'] = pd.to_datetime(dataset['Last_Login'], format='mixed').dt.strftime('%Y-%m-%d')

### c. Removing of Duplicates
Next, we will we will validate the entire dataset for duplicate. We will use the 'drop_duplicates()' to carry out this process.

In [277]:
# Remove duplicate records
dataset.drop_duplicates(inplace=True)

### d. Data Sorting
Next, we will sort the dataset using Subscription Date. This is make the dataset easily accesible to find information for any record using the customer Subscription date.

In [278]:
# Sort the dataset using customer date of Subscription
dataset.sort_values(by="Subscription_Date", ascending=True, axis=0, inplace=True)

In [279]:
# Confirm the first 20 records
dataset.head(n=20)

,Customer_ID,Order_ID,Subscription_Date,Product_ID,Product_Name,Category,Subscription_Type,Usage_Frequency,Revenue_Per_Customer,Payment_Plan,Discount_Applied,Support_Tickets,Feature_Adoption,Last_Login,Churn_Status,Customer_Tenure,Customer_Satisfaction,Marketing_Channel,Contract_Renewal,Num_Logins_Last_Month
15652,2522.0,79247.0,2022-01-01,20,APIConnect,Development Tools,Enterprise,Monthly,3981.0,Lifetime,24,8,99,2023-06-05,0,5,3,Email,1,29
23907,1162.0,20774.0,2022-01-01,4,PulseDesk,SaaS,Free,Daily,2623.0,Monthly,22,49,72,2023-09-17,1,4,1,Social Media,0,5
58459,4929.0,92139.0,2022-01-01,5,SentinelShield,Security,Basic,Monthly,4776.0,Annual,24,47,44,2023-07-20,0,2,3,Social Media,0,20
17587,62.0,88747.0,2022-01-01,17,CodeFusion,Development Tools,Basic,Daily,1182.0,Annual,4,47,20,2023-07-31,0,6,1,Social Media,1,7
42608,1969.0,12931.0,2022-01-01,6,FortiGateX,Security,Enterprise,Monthly,4618.0,Annual,6,3,59,2023-02-20,0,4,4,Referral,0,15
43153,488.0,15595.0,2022-01-01,6,FortiGateX,Security,Free,Weekly,1616.0,Monthly,14,49,82,2023-01-01,0,5,4,Referral,0,17
48207,128.0,41041.0,2022-01-01,8,SecureAuth,Security,Free,Monthly,3446.0,Lifetime,14,31,64,2023-11-15,0,7,4,Email,1,25
28413,4538.0,42836.0,2022-01-01,4,PulseDesk,SaaS,Pro,Weekly,1470.0,Monthly,4,15,68,2023-07-21,1,8,5,Social Media,0,27
40031,3544.0,437.0,2022-01-01,6,FortiGateX,Security,Basic,Daily,3679.0,Monthly,12,26,68,2023-01-19,0,1,1,Advertisement,1,2
36334,3690.0,82206.0,2022-01-01,2,TaskGenius,SaaS,Enterprise,Daily,3122.0,Monthly,21,49,69,2023-09-13,0,1,3,Social Media,1,0
19385,4795.0,97796.0,2022-01-01,19,ScriptEase,Development Tools,Basic,Daily,2978.0,Monthly,4,32,96,2023-12-27,0,1,4,Referral,1,3
5938,3891.0,30060.0,2022-01-01,17,CodeFusion,Development Tools,Enterprise,Monthly,4418.0,Monthly,18,27,87,2023-01-01,0,8,1,Referral,0,25
47777,4643.0,38862.0,2022-01-01,5,SentinelShield,Security,Enterprise,Weekly,1309.0,Annual,1,45,75,2023-04-08,0,6,3,Social Media,0,0
23398,1446.0,18200.0,2022-01-01,2,TaskGenius,SaaS,Pro,Weekly,4723.0,Lifetime,16,12,79,2023-04-16,1,6,2,Social Media,1,12
74503,2494.0,72221.0,2022-01-01,10,LinguoSense,Artificial Intelligence,Pro,Daily,1700.0,Annual,17,19,68,2023-07-05,0,6,1,Direct,1,25
71930,414.0,59508.0,2022-01-01,12,DeepMindX,Artificial Intelligence,Basic,Weekly,3905.0,Lifetime,23,45,79,2023-08-04,1,4,3,Direct,0,1
63251,192.0,16427.0,2022-01-01,12,DeepMindX,Artificial Intelligence,Pro,Monthly,3831.0,Annual,2,15,20,2023-03-27,0,8,5,Email,0,17
6400,4817.0,32314.0,2022-01-01,18,DevSync,Development Tools,Pro,Weekly,2259.0,Annual,14,0,68,2023-09-22,1,1,2,Direct,1,25
6150,2084.0,31016.0,2022-01-01,19,ScriptEase,Development Tools,Pro,Weekly,4599.0,Monthly,1,35,94,2023-04-14,0,1,4,Referral,0,26
16058,757.0,81185.0,2022-01-01,18,DevSync,Development Tools,Free,Weekly,4018.0,Monthly,17,22,36,2023-08-05,0,6,1,Email,0,25

In [280]:
# Check the count of all columns
dataset.count()

Customer_ID              99981
Order_ID                 99981
Subscription_Date        99981
Product_ID               99981
Product_Name             99981
Category                 99981
Subscription_Type        99981
Usage_Frequency          99981
Revenue_Per_Customer     99981
Payment_Plan             99981
Discount_Applied         99981
Support_Tickets          99981
Feature_Adoption         99981
Last_Login               99981
Churn_Status             99981
Customer_Tenure          99981
Customer_Satisfaction    99981
Marketing_Channel        99981
Contract_Renewal         99981
Num_Logins_Last_Month    99981
dtype: int64

### <u>4.0 Feature Engineering</u>
We will now create some new features in our dataset. These features are essential as they will provide more insight about the customers for better understanding.
- Customer_Lifetime_Value: 
- Engagement_Score:

In [281]:
# Feature Engineering
dataset['Customer_Lifetime_Value'] = dataset['Revenue_Per_Customer'] * dataset['Customer_Tenure']
dataset['Engagement_Score'] = dataset['Num_Logins_Last_Month'] + dataset['Feature_Adoption']

### <u>4.1 Data Transformation</u>
This step is done to transform all categorical variables to a numerical encoding for ML Model

In [282]:
# Data Transformation 1

# Define categorical columns
categorical_cols = ['Product_Name', 'Category', 'Subscription_Type', 'Usage_Frequency', 'Payment_Plan', 'Marketing_Channel']

# Initialize the encoder
label_encoder = LabelEncoder()

# Apply encoding to each column separately
for col in categorical_cols:
    dataset[col] = label_encoder.fit_transform(dataset[col])

### <u>Data Export of the cleaned dataset</u>
Lastly, We have concluded the dataset preparation as required. We will now export the dataset.
The dataset is fully ready for analysis and ML modeling

In [283]:
dataset.to_csv(path_or_buf="cognitive_cleaned_dataset.csv", index=False)